### ISSUE TITLE
Generator: GameWasOpened

### ISSUE THREAD

**Issue by michelgrootjans** [michelgrootjans/playing_with_projections#12]
:quiz_id, :game_id

**Comment by michelgrootjans** [comment]
Just to make sure, this is the chronological order of events for opening a game:

- Player1 opens a game => GameWasOpened + PlayerJoinedGame (the player that opened the game)
- Other players join.
- After 1 minute or 5 players in game => GameWasStarted
- Alternatively: noone joined => GameWasFinished

**Comment by tcoopman** [comment]
Do we want to send the same event GameWasFinished when the game was not actually started?

**Comment by michelgrootjans** [comment]
You're right, let's make it GameWasCanceled:

- Player1 opens a game => GameWasOpened + PlayerJoinedGame (the player that opened the game)
- Other players join.
- After 1 minute or 5 players in game => GameWasStarted
- Alternatively: noone joined => GameWasCanceled

**Comment by tcoopman** [comment]
Ok, added GameWasCancelled event.
