### ISSUE TITLE
Generator: Timestamps must be formatted in ISO 8601 (yyyy-MM-ddTHH:mm:ssZ)

### ISSUE THREAD

**Issue by tcoopman** [michelgrootjans/playing_with_projections#15]

**Comment by michelgrootjans** [comment]
Timestamps not ok in this format?
2016-09-03T19:25:42.166

**Comment by tcoopman** [comment]
Well, that's ok, but then what's the timezone? :-)

**Comment by michelgrootjans** [comment]
I'm assuming it is all expressed in UTC

**Comment by tcoopman** [comment]
that's the reason for the Z, but ok, I'll live with it

**Comment by tcoopman** [comment]
I still added Z. Easier to parse: https://github.com/michelgrootjans/playing_with_projections/commit/838b13581482275860ccc58496dd3a244acbc403#diff-4404e60946a3389cd3d3c53a661e3ec8R19

**Comment by michelgrootjans** [comment]
But doesn't yet work on the server ;-)

**Comment by tcoopman** [comment]
What doesn't work?
I generate a file and the server streams it just fine?

**Comment by michelgrootjans** [comment]
Was an out of date generated file.
