### ISSUE TITLE
Feedback from the DDDBER Workshop

### ISSUE THREAD

**Issue by rradczewski** [michelgrootjans/playing_with_projections#53]
We had several potential improvements (that I wouldn't create issues for without checking back with you first) coming up at our workshop yesterday:

- Adding a test runner to each language with the eventCounter being tested
- Adding a main that is "fairly" consistent between implementations so results are easier compared
- Removing all traces of "stream" and exclusively rely on `/data/*.json` files
- Organize the `/data/*.json` files and maybe remove a few of them

Let me know what you think :smile:

**Comment by tcoopman** [comment]
All of these sound fair. It would probably be better to create separate issues for these.

**Comment by rradczewski** [comment]
Closed in favor of #54, #55, #56, #57
